name: iOS Fastlane Firebase Distribution 

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  distribute_to_firebase_ios:
    runs-on: macos-latest

    steps:
    - name: Checkout my repo code
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.5'
        channel: stable

    - name: Install Flutter dependencies
      run: flutter pub get

    - name: Clean Flutter build
      run: flutter clean

    - name: Setup Ruby for Fastlane
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.2.3"
        bundler-cache: true
        working-directory: ios

    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods
        cd ios
        pod install --repo-update

    - name: Run Fastlane lane
      env:
        FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
      run: bundle exec fastlane firebase_distribution
      working-directory: ios

    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: ios-ipa
        path: ios/Runner.ipa
